# Generated by Django 6.0.7 on 2026-07-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 STAR'), (2, '2 STARS'), (3, '3 STARS'), (4, '4 STARS'), (5, '5 STARS')]),
        ),
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
