# Generated by Django 6.0.7 on 2026-07-18 22:24

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_username_review_name_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=100, validators=[main.validators.validate_comment]),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=10, validators=[main.validators.validate_name]),
        ),
    ]
