# Generated by Django 6.0.7 on 2026-07-18 22:42

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_review_comment_alter_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(validators=[main.validators.validate_comment]),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(validators=[main.validators.validate_name]),
        ),
    ]
